dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/1.1.0/bazel_1.1.0-linux-x86_64.deb
  - sha256sum -c tools/bazel_1.1.0-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_1.1.0-linux-x86_64.deb

script:
  - bazel build //cmd:all