
alias(
    name="web",
    actual="//cmd/web:web"
)

alias(
    name="fetch",
    actual="//cmd/fetch:fetch"
)

alias(
    name="db",
    actual="//cmd/db:db"
)

alias(
    name="analyze",
    actual="//cmd/analyze:analyze"
)
