alias(
    name = "web",
    actual = "//cmd/web:web",
)

alias(
    name = "fetch",
    actual = "//cmd/fetch:fetch",
)

alias(
    name = "fetch2",
    actual = "//cmd/fetch:fetch2",
)

alias(
    name = "db",
    actual = "//cmd/db:db",
)

alias(
    name = "analyze",
    actual = "//cmd/analyze:analyze",
)

alias(
    name = "client",
    actual = "//cmd/client:client",
)
