load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "analyticsclient",
    srcs = ["analyticsclient.go"],
    importpath = "github.com/MichiganDiningAPI/api/analytics/analyticsclient",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_glog//:go_default_library",
        "@com_github_google_uuid//:go_default_library",
    ],
)
